### ISSUE TITLE
Error: failed to find project

### ISSUE THREAD

**Issue by mbnoimi** [ceciletti/example-qt-cutelyst-rest#2]
Whenever I run the example I get this error message:
```
$ cutelyst2 -r --server --app-file src/libServerREST
Installing EPoll event loop
14301:14301 default[warning] QThread::setEventDispatcher: An event dispatcher has already been created for this thread
Error: failed to find project
Cutelyst-WSGI terminated
```
May you please tell me what's wrong?

**Comment by mbnoimi** [comment]
Strange!

Qt Creator set by default build folder to `~/Snippets/Qt/example-qt-cutelyst-rest/build-ServerREST-Desktop_System-Debug` so when I called the web app I get the above error **BUT** when I set Qt Creator build folder manually to `~/Snippets/Qt/example-qt-cutelyst-rest/ServerREST/build` the error disappear!

May you please explain to me what the hell happened?

**Comment by dantti** [comment]
cutelyst2 is a dev tool that tried to find your project on a build location that it created. It can't magically find out where you build it if you don't follow it's rules, so either point the app-file to the right location or follow it's default paths.

**Comment by mbnoimi** [comment]
PLEASE DON'T RUSH into the answer before reading the question:

`cutelyst2` doesn't accept to run any web app unless it's available in specific location which is very WEIRD behavior even if I pass the absolute path it doesn't accept it! See the following test:

I get the error when I call:
```
~ $ cutelyst2 -r --server --app-file /home/laptop/Snippets/Qt/example-qt-cutelyst-rest/build-ServerREST-Desktop_System-Debug/src/libServerREST
```
OR
```
~/Snippets/Qt/example-qt-cutelyst-rest/build-ServerREST-Desktop_System-Debug $ cutelyst2 -r --server --app-file /home/laptop/Snippets/Qt/example-qt-cutelyst-rest/build-ServerREST-Desktop_System-Debug/src/libServerREST
```
OR
```
~/Snippets/Qt/example-qt-cutelyst-rest/build-ServerREST-Desktop_System-Debug $ cutelyst2 -r --server --app-file src/libServerREST
```


The project structure is:
```
example-qt-cutelyst-rest
├── build-ServerREST-Desktop_System-Debug
│   ├── build.ninja
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   │   ├── 3.16.3
│   │   │   ├── CMakeCCompiler.cmake
│   │   │   ├── CMakeCXXCompiler.cmake
│   │   │   ├── CMakeDetermineCompilerABI_C.bin
│   │   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   │   ├── CMakeSystem.cmake
│   │   │   ├── CompilerIdC
│   │   │   │   ├── a.out
│   │   │   │   ├── CMakeCCompilerId.c
│   │   │   │   └── tmp
│   │   │   └── CompilerIdCXX
│   │   │       ├── a.out
│   │   │       ├── CMakeCXXCompilerId.cpp
│   │   │       └── tmp
│   │   ├── clean_additional.cmake
│   │   ├── cmake.check_cache
│   │   ├── CMakeOutput.log
│   │   ├── CMakeTmp
│   │   └── TargetDirectories.txt
│   ├── cmake_install.cmake
│   ├── qtcsettings.cmake
│   ├── rules.ninja
│   ├── ServerREST.cbp
│   └── src
│       ├── CMakeFiles
│       │   ├── ServerREST_autogen.dir
│       │   │   ├── AutogenInfo.json
│       │   │   ├── AutogenUsed.txt
│       │   │   └── ParseCache.txt
│       │   └── ServerREST.dir
│       │       ├── apiv1.cpp.o
│       │       ├── ServerREST_autogen
│       │       │   └── mocs_compilation.cpp.o
│       │       └── serverrest.cpp.o
│       ├── cmake_install.cmake
│       ├── libServerREST.so
│       └── ServerREST_autogen
│           ├── EWIEGA46WW
│           │   ├── moc_apiv1.cpp
│           │   └── moc_serverrest.cpp
│           ├── include
│           ├── moc_predefs.h
│           └── mocs_compilation.cpp
├── ClientREST
│   ├── CMakeLists.txt
│   ├── main.cpp
│   ├── mainwindow.cpp
│   ├── mainwindow.h
│   └── mainwindow.ui
├── README.md
└── ServerREST
    ├── CMakeLists.txt
    ├── CMakeLists.txt.user
    └── src
        ├── apiv1.cpp
        ├── apiv1.h
        ├── CMakeLists.txt
        ├── serverrest.cpp
        └── serverrest.h
```

**Comment by mbnoimi** [comment]
You mentioned that deploying Cutelyst is very easy. So I expect if I copied the generated binary (libServerREST.so) with needed static files (if available) to any path then called `cutelyst2 -r --server --app-file <path-to-libServerREST>` it should run but in my case it doesn't, so what I miss?

**Comment by mbnoimi** [comment]
I think I figure out what's the problem (I recorded it as a gif)
![Peek 2020-07-20 20-33](https://user-images.githubusercontent.com/284547/87968040-78f7d800-cac8-11ea-964a-7b96655609c1.gif)

This is really weird!

**Comment by dantti** [comment]
Again stop being harsh, cutelyst2 is a development tool, to be used for development following the proper paths, it will try to find your project, which is why it searches for CMakeList.txt.

> Error: failed to find project

It's not an error about finding your app file which you provided an absolute path, is your project that wasn't found so I'm still right. If you don't want this use cutelyst-wsgi2.

**Comment by mbnoimi** [comment]
> Again stop being harsh

I don't know how I was "harsh"!

> it will try to find your project, which is why it searches for CMakeList.txt.

That's mean I can't deploy any web app without its `CMakeList.txt` does it?
BTW, I consider my questions are very fair because the wiki doesn't mention anything about "how to deploy" so how can I know that `CMakeList.txt` is needed to deploy?!

**Comment by dantti** [comment]
All caps is usually not polite, I wasn't rushing into replying I just replied what the error was

>That's mean I can't deploy any web app without its CMakeList.txt does it?

Yes, you can, CMakeLists.txt is only needed by cutelyst2 executable because it's a helper development tool, on production you only need you .so file and cutelyst-wsgi2 or create an executable that links to it.

Yes, a deploy page would surely be helpful.

**Comment by mbnoimi** [comment]
> All caps is usually not polite

Sorry I used caps for pointing to my saying I didn't mention to be rude.

> Yes, you can, CMakeLists.txt is only needed by cutelyst2 executable because it's a helper development tool, on production you only need you .so file and cutelyst-wsgi2 or create an executable that links to it.

Oops, I though `cutelyst2` works as a production tool! I though `cutelyst2` is the mentioned engine in [this wiki page](https://github.com/cutelyst/cutelyst/wiki/EngineCutelystWSGI)

> Yes, a deploy page would surely be helpful.

YES, YES, YES 
The only valuable docs for newbies are tutorial pages while the others are foggy (I learned from the available issues more than project's docs)

**Comment by dantti** [comment]
The binaries cutelyst2 and cutelyst-wsgi2 have the exactly same engine, but their purpose is different, cutelyst2 can create a basic project and help starting the server, cutelyst-wsg2 is just the engine to be used in production.
